name: Publish Release

on:
  workflow_dispatch:

jobs:
  skip:
    name: Skipped
    if: ${{ !startsWith(github.ref_name, 'release-') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This workflow only runs on the 'release-*' branches"
          exit 1

  ci:
    name: CI
    if: ${{ startsWith(github.ref_name, 'release-') }}
    uses: augentic/.github/.github/workflows/ci.yaml@main
    secrets: inherit

  publish:
    name: Publish
    needs: ci
    uses: augentic/.github/.github/workflows/publish.yaml@main

  deploy:
    name: Deploy
    needs: publish
    uses: augentic/.github/.github/workflows/wasm.yaml@main
    secrets: inherit
    with:
      package: <PACKAGE_NAME>
      storage-account: <STORAGE_ACCOUNT>
      resource-group: <RESOURCE_GROUP>
