[package]
name = "pulse-adapter"
description = "Pulse position adapter"
readme = "README.md"
publish = false
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
acme-common.workspace = true
anyhow.workspace = true
bytes.workspace = true
chrono.workspace = true
http.workspace = true
http-body-util.workspace = true
omnia-guest.workspace = true
quick-xml.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_repr.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
augentic-test.workspace = true
http-body.workspace = true
tokio.workspace = true
