[package]
name = "common"
description = "Common transit domain logic"
readme = "README.md"
publish = false
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
chrono-tz.workspace = true
http.workspace = true
http-body-util.workspace = true
omnia-guest.workspace = true
serde.workspace = true
serde_json.workspace = true
urlencoding.workspace = true
